substitutions:
  _REGION: us-east1
  _PROJECT: housing-app-490522

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'us-east1-docker.pkg.dev/${_PROJECT}/housing-app/neighborhood-svc:latest', './services/neighborhood']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/${_PROJECT}/housing-app/neighborhood-svc:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'us-east1-docker.pkg.dev/${_PROJECT}/housing-app/predictor-svc:latest', './services/predictor']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/${_PROJECT}/housing-app/predictor-svc:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'us-east1-docker.pkg.dev/${_PROJECT}/housing-app/dashboard-svc:latest', './services/dashboard']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/${_PROJECT}/housing-app/dashboard-svc:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'us-east1-docker.pkg.dev/${_PROJECT}/housing-app/recommender-svc:latest', './services/recommender']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/${_PROJECT}/housing-app/recommender-svc:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'us-east1-docker.pkg.dev/${_PROJECT}/housing-app/frontend:latest', './frontend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/${_PROJECT}/housing-app/frontend:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'bash'
      - '-c'
      - |
        gcloud run deploy neighborhood-svc --image=us-east1-docker.pkg.dev/${_PROJECT}/housing-app/neighborhood-svc:latest --region=${_REGION} --project=${_PROJECT} &&
        gcloud run deploy predictor-svc --image=us-east1-docker.pkg.dev/${_PROJECT}/housing-app/predictor-svc:latest --region=${_REGION} --project=${_PROJECT} &&
        gcloud run deploy dashboard-svc --image=us-east1-docker.pkg.dev/${_PROJECT}/housing-app/dashboard-svc:latest --region=${_REGION} --project=${_PROJECT} &&
        gcloud run deploy recommender-svc --image=us-east1-docker.pkg.dev/${_PROJECT}/housing-app/recommender-svc:latest --region=${_REGION} --project=${_PROJECT} &&
        gcloud run deploy frontend --image=us-east1-docker.pkg.dev/${_PROJECT}/housing-app/frontend:latest --region=${_REGION} --project=${_PROJECT}

options:
  logging: CLOUD_LOGGING_ONLY